name: deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Compress Files
        run: zip --symlinks -r my-api.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_SECRET}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Init Elastic Beanstalk
        run: echo "n" | eb init nestjs-eb --region ${{secrets.AWS_REGION}}

      - name: Deploy to Elastic Beanstalk
        run: eb deploy nestjs-eb-env --staged --label test-my-api-${{github.event.repository.pushed_at}}
